# Dataset config
dataset_window_size: 40
dataset_shift_size: 1
dataset_num_exclude: 0
dataset_use_tree_structure: True 
dataset_use_scaled: True


# BNLSTM model config
bnlstm_hidden_size: 256
bnlstm_n_layers: 2
bnlstm_dropout: 0.5


# Test configs
batch_size: 128


# Saving configs
checkpoint_paths: [
  "model_checkpoints/supervised/2021.04.28-23:35:56-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-model_BNLSTM-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=43-val_acc_epoch=0.8081.ckpt", #256_40_normal
  "model_checkpoints/supervised/2021.04.28-07:54:07-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-model_BNLSTM-modelHS_128-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=42-val_acc_epoch=0.7907.ckpt", #128_40_normal
  "model_checkpoints/supervised/2021.04.29-19:35:50-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-model_BNLSTM-modelHS_64-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=40-val_acc_epoch=0.7627.ckpt", #64_40_normal

  "model_checkpoints/supervised/2021.04.29-23:47:00-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-model_BNLSTM-modelHS_256-modelNL4-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=45-val_acc_epoch=0.8104.ckpt", #256_40_NL4
  "model_checkpoints/supervised/2021.04.30-15:20:12-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_False-dsUTS_True-model_BNLSTM-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=47-val_acc_epoch=0.8494.ckpt", #256_40_USFalse
  "model_checkpoints/supervised/2021.05.01-18:13:35-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_100-dsUS_True-dsUTS_True-model_BNLSTM-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=48-val_acc_epoch=0.8361.ckpt", #256_40_NE100
  "model_checkpoints/supervised/2021.05.08-17:30:51-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_20-dsUS_True-dsUTS_True-model_BNLSTM-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=49-val_acc_epoch=0.8147.ckpt", #256_40_NE20

  "model_checkpoints/supervised/2021.04.30-13:55:55-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-model_LOGREG-modelHS_256-modelNL2-modelDOUT_0-loss_BCEWLL-lossUW_False-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=34-val_acc_epoch=0.0520.ckpt", # LOGREG
  "model_checkpoints/supervised/2021.04.30-10:03:47-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-model_LSTM-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-optLR_0.001-optWD_1e-06-sched_MultiStepLR-schedMS_[20, 40, 60, 80]-schedGAM_0.33/epoch=46-val_acc_epoch=0.4385.ckpt", #LSTM
  
  "model_checkpoints/supervised/2021.05.12-16:12:26-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-dsUSSL_True-model_BNLSTM-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-sched_MultiStepLR/epoch=49-val_acc_epoch=0.4691.ckpt",  # NO SSL PRETRAIN
  "model_checkpoints/supervised/2021.05.13-18:18:25-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-dsUSSL_True-model_SelfSupervised-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-sched_MultiStepLR/epoch=50-val_acc_epoch=0.4537.ckpt", # SSL pretrain, epoch: 51, beta: 0.6
  "model_checkpoints/supervised/2021.05.12-21:33:09-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-dsUSSL_True-model_SelfSupervised-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-sched_MultiStepLR/epoch=47-val_acc_epoch=0.4662.ckpt", # SSL pretrain, epoch: 51, beta: 0.8
  "model_checkpoints/supervised/2021.05.13-14:23:14-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-dsUSSL_True-model_SelfSupervised-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-sched_MultiStepLR/epoch=20-val_acc_epoch=0.4558.ckpt", # SSL pretrain, epoch: 101, beta: 0.95
  "model_checkpoints/supervised/2021.05.13-14:23:14-epochs_51-bs_128-dsWS_40-dsSS_1-dsNE_0-dsUS_True-dsUTS_True-dsUSSL_True-model_SelfSupervised-modelHS_256-modelNL2-modelDOUT_0.5-loss_CrossEntropyLoss-lossUW_True-opt_Adam-sched_MultiStepLR/epoch=50-val_acc_epoch=0.4578.ckpt" # SSL pretrain, epoch: 101, beta: 0.95
  ]
save_eps: True


